package au.edu.ardc.registry.common.model;

public enum Attribute {

	// core attributes
	DATA_PATH, LOG_PATH,

	// extended attributes
	CREATOR_ID, OWNER_TYPE, OWNER_ID, ALLOCATION_ID, ALLOCATION_PREFIX, REQUESTED_IDENTIFIERS_PATH, IMPORTED_IDENTIFIERS_PATH, PAYLOAD_PATH, CHUNKED_PAYLOAD_PATH, SCHEMA_ID,

	// job type
	EVENT_TYPE,

	// summary
	NUM_OF_RECORDS_RECEIVED, NUM_OF_RECORDS_CREATED, NUM_OF_RECORDS_UPDATED, NUM_OF_IGSN_REGISTERED,

	// summary error
	NUM_OF_ERROR, NUM_OF_RECORD_ALREADY_EXISTS, NUM_OF_RECORDS_FORBIDDEN, NUM_OF_RECORD_CONTENT_NOT_CHANGED, NUM_OF_FAILED_REGISTRATION,

	// bench marks
	START_TIME_CHUNKING, START_TIME_IMPORT, START_TIME_UPDATE, START_TIME_REGISTER,
	END_TIME_CHUNKING, END_TIME_IMPORT, END_TIME_UPDATE, END_TIME_REGISTER


}
