package au.edu.ardc.igsn.entity;


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;
import java.util.UUID;

@Entity
@Table(name = "versions")
public class Version {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(
            name = "UUID",
            strategy = "org.hibernate.id.UUIDGenerator"
    )
    @Column(columnDefinition = "BINARY(16)", updatable = false, nullable = false, unique = true)
    private UUID id;

    @Enumerated(EnumType.STRING)
    private Status status;

    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    @Temporal(TemporalType.TIMESTAMP)
    private Date endedAt;

    @Column(columnDefinition = "BINARY(16)")
    private UUID creatorID;

    @ManyToOne
    @JoinColumn(name = "record_id", nullable = false)
    private Record record;

    /**
     * Empty constructor
     */
    public Version (){

    }

    /**
     * Constructor with uuid
     * Keep in mind the record once persist will have the uuid generated by Hibernate
     *
     * @param uuid the UUID to instantiate this record for
     */
    public Version(UUID uuid) {
        this.id = uuid;
    }

    public Record getRecord() {
        return record;
    }

    public void setRecord(Record record) {
        this.record = record;
    }

    public UUID getId() {
        return id;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getEndedAt() {
        return endedAt;
    }

    public void setEndedAt(Date endedAt) {
        this.endedAt = endedAt;
    }

    public UUID getCreatorID() {
        return creatorID;
    }

    public void setCreatorID(UUID creatorID) {
        this.creatorID = creatorID;
    }

    public static enum Status {
        CURRENT, SUPERSEDED
    }

}
